module.exports = {
	PLAY_TRACK : "PLAY",
	PAUSE_TRACK : "PAUSE",
	NEXT_TRACK : "NEXT",
	PREVIOUS_TRACK : "PREVIOUS",

	ADD_ITEM : "ADD",
	INCREASE_ITEM : "INCREASE",
	REMOVE_ITEM : "REMOVE",
	DECREASE_ITEM : "DECREASE"
};